begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select plan(9);
select ok(not has_function_privilege('authenticated','public.task_pool_claim(text,text[],uuid)','EXECUTE'), 'targeted RPC denied to authenticated');
select ok(not has_function_privilege('anon','public.task_pool_claim(text,text[],uuid)','EXECUTE'), 'targeted RPC denied to anon');
create temporary table smoke_instruction as select '{"schema_version":1,"summary":"Smoke","objective":"Read only","scope":["README"],"constraints":[],"inputs":[],"acceptance_criteria":[{"id":"c1","expectation":"Report"}],"deliverables":["Report"]}'::jsonb as instruction;
select public.task_pool_delegate('pm','target-prior','SmokeSql',null,(select instruction from smoke_instruction));
create temporary table target as select public.task_pool_delegate('pm','target-only','SmokeSql',null,(select instruction from smoke_instruction)) as task;
select public.task_pool_delegate('pm','target-after','SmokeSql',null,(select instruction from smoke_instruction));
select ok((public.task_pool_claim('host',array['Other'],(select (task).id from target))).id is null, 'project restriction retained');
select is((select count(*)::integer from tasks_pool where project='SmokeSql' and claimed_by is null),3,'wrong project changes no ownership');
select is((public.task_pool_claim('host',array['SmokeSql'],(select (task).id from target))).id,(select (task).id from target),'exact target claimed');
select is((select count(*)::integer from tasks_pool where project='SmokeSql' and claimed_by is null),2,'unrelated before/after remain queued');
select ok((public.task_pool_claim('other',array['SmokeSql'],(select (task).id from target))).id is null,'owned target cannot be reclaimed or cause fallback');
select is((select claimed_by from tasks_pool where key='target-only'),'host','target ownership stays sticky');
select throws_ok($$select public.task_pool_claim('host',array['SmokeSql'],null::uuid)$$,'22023','Invalid task request','null exact ID never becomes broad claim');
select * from finish();
rollback;
