begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select plan(47);
select has_table('public', 'tasks_pool', 'one task persistence table exists');
select is((select count(*)::integer from information_schema.columns where table_schema='public' and table_name='tasks_pool'), 13, 'exactly thirteen lifecycle columns');
select ok(not has_table_privilege('anon','public.tasks_pool','SELECT'), 'anon table denied');
select ok(not has_table_privilege('authenticated','public.tasks_pool','INSERT'), 'authenticated writes denied');
select ok((select relrowsecurity from pg_class where oid='public.tasks_pool'::regclass), 'RLS enabled');
select ok(not has_function_privilege('authenticated','public.task_pool_claim(text,text[])','EXECUTE'), 'claim RPC denied');
select ok(not has_function_privilege('anon','public.task_pool_finalize(text,uuid,jsonb)','EXECUTE'), 'finalize RPC denied');
select ok(not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'task_pool_%' and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE'))), 'all task RPCs/helpers revoked from public callers');
select ok(not exists (select 1 from pg_publication_tables where schemaname='public' and tablename='tasks_pool'), 'no task row publication');
select ok(not exists (select 1 from pg_policies where schemaname='realtime' and tablename='messages' and cmd in ('INSERT','ALL') and ('authenticated'=any(roles) or 'public'=any(roles))), 'no authenticated Realtime SEND policy');
select is((select count(*)::integer from pg_indexes where schemaname='public' and tablename='tasks_pool' and indexdef like '% WHERE %'),2,'two partial indexes');
select ok(not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'task_pool_%' and not coalesce(p.proconfig @> array['search_path=""'],false)), 'all task functions use empty search_path');
create temporary table fixture as select public.task_pool_delegate('pm','sql-task','SqlProject',null,
  '{"schema_version":1,"summary":"Task","objective":"Work","scope":["Parser"],"constraints":[],"inputs":[],"acceptance_criteria":[{"id":"c1","expectation":"Pass"}],"deliverables":["Tests"]}'::jsonb) as task;
select is((public.task_pool_delegate('pm','sql-task','SqlProject',null,(select (task).instruction from fixture))).id, (select (task).id from fixture), 'identical delegate retry');
select throws_ok($$select public.task_pool_delegate('tl','sql-task','SqlProject',null,(select (task).instruction from fixture))$$,'PT409','Task conflict','key conflict');
select throws_ok($$update tasks_pool set claimed_by='host' where key='sql-task'$$,'23514',null,'ownership null pair');
select throws_ok($$update tasks_pool set opencode_session_id='s' where key='sql-task'$$,'23514',null,'binding needs owner');
select throws_ok($$update tasks_pool set project='Other' where key='sql-task'$$,'PT409','Task conflict','immutable delegation');
select lives_ok($$select public.task_pool_claim('host',array['SqlProject'])$$,'atomic claim');
select is((select claimed_by from tasks_pool where key='sql-task'),'host','owner persisted');
select throws_ok($$update tasks_pool set claimed_by='other' where key='sql-task'$$,'PT409','Task conflict','sticky owner');
select throws_ok($$select public.task_pool_bind('other',(select (task).id from fixture),'s')$$,'PT403','Task forbidden','wrong owner');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"completed","summary":"Done","checks":[{"criterion_id":"c1","result":"passed","evidence":[{"locator":"tests","description":"Pass"}]}],"artifacts":[],"failure":null}')$$,'22023','Invalid task report','completed requires session');
select lives_ok($$select public.task_pool_bind('host',(select (task).id from fixture),'session-sql')$$,'bind');
select lives_ok($$select public.task_pool_bind('host',(select (task).id from fixture),'session-sql')$$,'bind retry');
select throws_ok($$select public.task_pool_bind('host',(select (task).id from fixture),'different')$$,'PT409','Task conflict','binding immutable');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"completed","summary":"Done","checks":[],"artifacts":[],"failure":null}')$$,'22023','Invalid task report','criterion coverage');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[{"criterion_id":"unknown","result":"failed","evidence":[]}],"artifacts":[],"failure":"Build failed"}')$$,'22023','Invalid task report','unknown criterion rejected');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"completed","summary":"Done","checks":[{"criterion_id":"c1","result":"passed","evidence":[]}],"artifacts":[],"failure":null}')$$,'22023','Invalid task report','completion evidence required');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[],"artifacts":[],"failure":null}')$$,'22023','Invalid task report','failure explanation required');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[],"artifacts":[],"failure":"Build failed","recipient":"evil"}')$$,'22023','Invalid task report','arbitrary daemon mail forbidden');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),jsonb_build_object('schema_version',1,'state','failed','summary','Failed','checks','[]'::jsonb,'artifacts',(select jsonb_agg(jsonb_build_object('locator','tests','description',repeat('x',4000))) from generate_series(1,30)),'failure','Build failed'))$$,'22023','Invalid task report','database rejects oversized report before mail');
select lives_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[],"artifacts":[],"failure":"Build failed"}')$$,'failed report');
select is((select count(*)::integer from agent_messages where sender='worker.host'),1,'one atomic mail');
select lives_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"failure":"Build failed","artifacts":[],"checks":[],"summary":"Failed","state":"failed","schema_version":1}')$$,'semantic terminal retry');
select throws_ok($$select public.task_pool_finalize('host',(select (task).id from fixture),'{"schema_version":1,"state":"failed","summary":"Different","checks":[],"artifacts":[],"failure":"Build failed"}')$$,'PT409','Task conflict','terminal conflict');
select throws_ok($$update tasks_pool set finished_at=now()+interval '1 day' where key='sql-task'$$,'PT409','Task conflict','terminal immutable');
select throws_ok($$update tasks_pool set result_message_ref=null where key='sql-task'$$,'PT409','Task conflict','finalized mail reference cannot clear');
select throws_ok($$select public.task_pool_delegate('pm','invalid-instruction','SqlProject',null,'{}')$$,'22023','Invalid task request','instruction validated in DB');
select throws_ok($$select public.task_pool_delegate('pm','invalid-project','../escape',null,(select (task).instruction from fixture))$$,'22023','Invalid task request','project validated in DB');
select throws_ok($$insert into tasks_pool(key,project,delegator_role,instruction,finished_at) select 'null-finish','SqlProject','pm',(task).instruction,now() from fixture$$,'23514',null,'report/finish pair');
select lives_ok($$select public.task_pool_delegate('tl','pre-session','SqlProject',null,(select (task).instruction from fixture)); select public.task_pool_claim('prehost',array['SqlProject'])$$,'pre-session claim');
select throws_ok($$select public.task_pool_finalize('prehost',(select id from tasks_pool where key='pre-session'),'{"schema_version":1,"state":null,"summary":"Bad","checks":[],"artifacts":[],"failure":"Bad"}')$$,'22023','Invalid task report','null report state rejected');
create function pg_temp.fail_task_finish() returns trigger language plpgsql as $$ begin if new.key='pre-session' and new.terminal_report is not null then raise exception 'injected finalization failure'; end if; return new; end $$;
create trigger task_test_fail before update on tasks_pool for each row execute function pg_temp.fail_task_finish();
select throws_ok($$select public.task_pool_finalize('prehost',(select id from tasks_pool where key='pre-session'),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[],"artifacts":[],"failure":"Preparation failed"}')$$,'P0001','injected finalization failure','failure after mail insert');
select is((select count(*)::integer from agent_messages where sender='worker.prehost'),0,'mail insert rolled back');
select ok((select terminal_report is null and finished_at is null and result_message_ref is null from tasks_pool where key='pre-session'),'task finalization rolled back');
drop trigger task_test_fail on tasks_pool;
select lives_ok($$select public.task_pool_finalize('prehost',(select id from tasks_pool where key='pre-session'),'{"schema_version":1,"state":"failed","summary":"Failed","checks":[],"artifacts":[],"failure":"Preparation failed"}')$$,'pre-session failure can finalize');
select ok((select opencode_session_id is null and terminal_report is not null from tasks_pool where key='pre-session'),'failure without session');
select * from finish();
rollback;
